import { ComponentType } from 'react'

export interface ToolConfig {
  id: string
  name: string
  description: string
  category: string
  icon: string
  features: string[]
  keywords: string[]
  popular?: boolean
}

// Tool registry - This will be populated as we build each tool
export const toolRegistry: ToolConfig[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify JSON with syntax highlighting. Detect errors with line numbers.',
    category: 'formatters',
    icon: '{ }',
    features: [
      'Syntax highlighting',
      'Error detection with line numbers',
      'Configurable indentation (2/4 spaces, tabs)',
      'Minify option',
      'Copy and download formatted JSON',
      '100% client-side processing',
    ],
    keywords: ['json', 'format', 'validate', 'beautify', 'minify', 'formatter'],
    popular: true,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode and decode Base64 strings instantly. Supports text and URL-safe encoding.',
    category: 'security',
    icon: '⇄',
    features: [
      'Encode text to Base64',
      'Decode Base64 to text',
      'URL-safe encoding option',
      'Error handling for invalid Base64',
      'Copy and download results',
      'Instant conversion',
    ],
    keywords: ['base64', 'encode', 'decode', 'encoder', 'decoder'],
    popular: true,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode and decode URL strings. Supports full URL and component encoding.',
    category: 'conversion',
    icon: '🔗',
    features: [
      'Encode URL components',
      'Decode URL-encoded strings',
      'Full URL vs component encoding',
      'Handle special characters',
      'Copy results instantly',
      'No server processing',
    ],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    popular: true,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers (UUID v4). Supports bulk generation and formatting options.',
    category: 'generators',
    icon: '🆔',
    features: [
      'Generate UUID v4 (random)',
      'Bulk generation (1-100 UUIDs)',
      'Uppercase/lowercase options',
      'Copy all UUIDs',
      'Download as text file',
      'Cryptographically secure',
    ],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    popular: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs. Choose words, sentences, or paragraphs.',
    category: 'generators',
    icon: '📄',
    features: [
      'Generate words, sentences, or paragraphs',
      'Customizable count (1-100)',
      'Start with "Lorem ipsum" option',
      'Copy generated text',
      'Download as text file',
      'Classic Lorem Ipsum text',
    ],
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generator', 'dummy'],
    popular: true,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512) from any text.',
    category: 'security',
    icon: '#️⃣',
    features: [
      'MD5 hash generation',
      'SHA-1 hash generation',
      'SHA-256 hash generation',
      'SHA-512 hash generation',
      'All hashes generated simultaneously',
      'Copy individual or all hashes',
    ],
    keywords: ['hash', 'md5', 'sha', 'sha1', 'sha256', 'sha512', 'checksum', 'crypto'],
    popular: false,
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text between different cases: uppercase, lowercase, camelCase, snake_case, and more.',
    category: 'text-transformers',
    icon: '🔤',
    features: [
      'UPPERCASE conversion',
      'lowercase conversion',
      'Title Case conversion',
      'camelCase conversion',
      'PascalCase conversion',
      'snake_case conversion',
      'kebab-case conversion',
      'CONSTANT_CASE conversion',
      'Sentence case conversion',
    ],
    keywords: ['case', 'convert', 'uppercase', 'lowercase', 'camel', 'snake', 'kebab', 'pascal'],
    popular: false,
  },
  {
    id: 'text-diff-checker',
    name: 'Text Diff Checker',
    description: 'Compare two texts side-by-side. Find differences in lines, words, and characters.',
    category: 'text-transformers',
    icon: '📊',
    features: [
      'Side-by-side comparison',
      'Line difference count',
      'Word difference count',
      'Character difference count',
      'Detailed statistics',
      'Clear visualization',
    ],
    keywords: ['diff', 'compare', 'difference', 'text', 'compare', 'checker'],
    popular: false,
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter & Minifier',
    description: 'Format and beautify HTML code. Minify HTML to reduce file size.',
    category: 'formatters',
    icon: '</>',
    features: [
      'Format HTML with proper indentation',
      'Minify HTML (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Syntax preservation',
      'Fast processing',
    ],
    keywords: ['html', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: false,
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter & Minifier',
    description: 'Format and beautify CSS code. Minify CSS to reduce file size.',
    category: 'formatters',
    icon: '🎨',
    features: [
      'Format CSS with proper indentation',
      'Minify CSS (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Preserve CSS rules',
      'Fast processing',
    ],
    keywords: ['css', 'format', 'minify', 'beautify', 'formatter', 'compress', 'stylesheet'],
    popular: false,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor & Previewer',
    description: 'Write and preview Markdown in real-time. See your formatted content as you type.',
    category: 'text-transformers',
    icon: '📝',
    features: [
      'Live HTML preview',
      'Support for headers, bold, italic',
      'Code blocks and inline code',
      'Links and lists',
      'Split-panel view',
      'Instant rendering',
    ],
    keywords: ['markdown', 'md', 'editor', 'preview', 'html', 'formatting'],
    popular: true,
  },
  {
    id: 'color-picker',
    name: 'Color Picker & Converter',
    description: 'Pick colors and convert between HEX, RGB, and HSL formats instantly.',
    category: 'conversion',
    icon: '🎨',
    features: [
      'Visual color picker',
      'HEX color codes',
      'RGB color values',
      'HSL color values',
      'Copy any format',
      'Live color preview',
    ],
    keywords: ['color', 'picker', 'hex', 'rgb', 'hsl', 'converter', 'palette'],
    popular: true,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates. Supports ISO 8601 format.',
    category: 'conversion',
    icon: '🕐',
    features: [
      'Unix to Date conversion',
      'Date to Unix conversion',
      'ISO 8601 format support',
      'Current timestamp display',
      'Formatted date output',
      'Use current time button',
    ],
    keywords: ['timestamp', 'unix', 'date', 'time', 'convert', 'epoch', 'iso'],
    popular: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester & Validator',
    description: 'Test regular expressions with live matching. Supports flags and pattern validation.',
    category: 'text-transformers',
    icon: '🔍',
    features: [
      'Live regex testing',
      'Pattern validation',
      'Global, ignore case, multiline flags',
      'Match highlighting',
      'Match count and results',
      'Common flag presets',
    ],
    keywords: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test', 'validate'],
    popular: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder & Inspector',
    description: 'Decode and inspect JSON Web Tokens (JWT). View header, payload, and signature.',
    category: 'security',
    icon: '🔓',
    features: [
      'Decode JWT tokens',
      'Display header and payload',
      'Show signature',
      'Parse standard claims (iat, exp, nbf)',
      'Expiration checking',
      'Copy decoded parts',
    ],
    keywords: ['jwt', 'json web token', 'decode', 'inspect', 'token', 'auth', 'security'],
    popular: true,
  },
  {
    id: 'javascript-formatter',
    name: 'JavaScript Formatter & Minifier',
    description: 'Format and beautify JavaScript code. Minify JS to reduce file size.',
    category: 'formatters',
    icon: '⚡',
    features: [
      'Format JavaScript with proper indentation',
      'Minify JavaScript (remove whitespace & comments)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Syntax preservation',
      'Fast processing',
    ],
    keywords: ['javascript', 'js', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: true,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries. Proper indentation and keyword capitalization.',
    category: 'formatters',
    icon: '💾',
    features: [
      'Format SQL with proper indentation',
      'Keyword capitalization',
      'Support for common SQL operations',
      'JOIN formatting',
      'Nested query indentation',
      'Copy formatted SQL',
    ],
    keywords: ['sql', 'format', 'beautify', 'query', 'database', 'formatter'],
    popular: true,
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs. Download as PNG image.',
    category: 'generators',
    icon: '📱',
    features: [
      'Generate QR codes from any text',
      'URL encoding support',
      'Configurable size (128px, 256px, 512px)',
      'Download as PNG',
      'Instant generation',
      'Visual preview',
    ],
    keywords: ['qr', 'qr code', 'barcode', 'generate', 'url', 'mobile'],
    popular: true,
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64 Converter',
    description: 'Convert images to Base64 strings. Perfect for embedding in HTML, CSS, or JSON.',
    category: 'conversion',
    icon: '🖼️',
    features: [
      'Upload any image format',
      'Convert to Base64 string',
      'Image preview',
      'File size information',
      'Copy Base64 string',
      'Support for all image types',
    ],
    keywords: ['image', 'base64', 'convert', 'encode', 'embed', 'data uri'],
    popular: true,
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions. See human-readable schedules.',
    category: 'text-transformers',
    icon: '⏰',
    features: [
      'Parse cron expressions',
      'Human-readable descriptions',
      'Expression validation',
      'Common presets',
      'Part-by-part breakdown',
      'Schedule explanation',
    ],
    keywords: ['cron', 'schedule', 'parser', 'expression', 'time', 'job', 'task'],
    popular: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter & Minifier',
    description: 'Format and beautify XML. Minify XML to reduce file size.',
    category: 'formatters',
    icon: '📋',
    features: [
      'Format XML with proper indentation',
      'Minify XML (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Preserve XML structure',
      'Fast processing',
    ],
    keywords: ['xml', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: true,
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate JSON Web Tokens with custom payload and expiration.',
    category: 'security',
    icon: '🔑',
    features: [
      'Generate JWT tokens',
      'Custom payload (JSON)',
      'Configurable secret key',
      'Expiration time presets',
      'View token parts (header, payload, signature)',
      'Copy generated token',
    ],
    keywords: ['jwt', 'json web token', 'generate', 'token', 'auth', 'security'],
    popular: true,
  },
  {
    id: 'csv-json-converter',
    name: 'CSV to JSON Converter',
    description: 'Convert between CSV and JSON formats. Bi-directional conversion.',
    category: 'conversion',
    icon: '🔄',
    features: [
      'CSV to JSON conversion',
      'JSON to CSV conversion',
      'Bi-directional with swap',
      'Auto-detect headers',
      'Number type parsing',
      'Quote handling for commas',
    ],
    keywords: ['csv', 'json', 'convert', 'converter', 'data', 'table', 'spreadsheet'],
    popular: true,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords with customizable options.',
    category: 'generators',
    icon: '🔐',
    features: [
      'Cryptographically secure generation',
      'Adjustable length (4-64 characters)',
      'Uppercase/lowercase options',
      'Numbers and symbols',
      'Password strength indicator',
      'One-click copy',
    ],
    keywords: ['password', 'generate', 'generator', 'secure', 'random', 'strong'],
    popular: true,
  },
  {
    id: 'json-yaml-converter',
    name: 'JSON to YAML Converter',
    description: 'Convert between JSON and YAML formats. Bi-directional conversion.',
    category: 'conversion',
    icon: '↔️',
    features: [
      'JSON to YAML conversion',
      'YAML to JSON conversion',
      'Bi-directional with swap',
      'Configurable YAML indentation',
      'Syntax examples included',
      'Comment preservation (YAML)',
    ],
    keywords: ['json', 'yaml', 'yml', 'convert', 'converter', 'config', 'configuration'],
    popular: true,
  },
]

// Helper function to get tool by ID
export function getToolById(id: string): ToolConfig | undefined {
  return toolRegistry.find((tool) => tool.id === id)
}

// Helper function to get tools by category
export function getToolsByCategory(category: string): ToolConfig[] {
  return toolRegistry.filter((tool) => tool.category === category)
}

// Helper function to get popular tools
export function getPopularTools(): ToolConfig[] {
  return toolRegistry.filter((tool) => tool.popular)
}
