import { ComponentType } from 'react'

export interface ToolConfig {
  id: string
  name: string
  description: string
  category: string
  icon: string
  features: string[]
  keywords: string[]
  popular?: boolean
}

// Tool registry - This will be populated as we build each tool
export const toolRegistry: ToolConfig[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify JSON with syntax highlighting. Detect errors with line numbers.',
    category: 'formatters',
    icon: '{ }',
    features: [
      'Syntax highlighting',
      'Error detection with line numbers',
      'Configurable indentation (2/4 spaces, tabs)',
      'Minify option',
      'Copy and download formatted JSON',
      '100% client-side processing',
    ],
    keywords: ['json', 'format', 'validate', 'beautify', 'minify', 'formatter'],
    popular: true,
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode and decode Base64 strings instantly. Supports text and URL-safe encoding.',
    category: 'security',
    icon: '⇄',
    features: [
      'Encode text to Base64',
      'Decode Base64 to text',
      'URL-safe encoding option',
      'Error handling for invalid Base64',
      'Copy and download results',
      'Instant conversion',
    ],
    keywords: ['base64', 'encode', 'decode', 'encoder', 'decoder'],
    popular: true,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode and decode URL strings. Supports full URL and component encoding.',
    category: 'conversion',
    icon: '🔗',
    features: [
      'Encode URL components',
      'Decode URL-encoded strings',
      'Full URL vs component encoding',
      'Handle special characters',
      'Copy results instantly',
      'No server processing',
    ],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    popular: true,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate unique identifiers (UUID v4). Supports bulk generation and formatting options.',
    category: 'generators',
    icon: '🆔',
    features: [
      'Generate UUID v4 (random)',
      'Bulk generation (1-100 UUIDs)',
      'Uppercase/lowercase options',
      'Copy all UUIDs',
      'Download as text file',
      'Cryptographically secure',
    ],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    popular: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs. Choose words, sentences, or paragraphs.',
    category: 'generators',
    icon: '📄',
    features: [
      'Generate words, sentences, or paragraphs',
      'Customizable count (1-100)',
      'Start with "Lorem ipsum" option',
      'Copy generated text',
      'Download as text file',
      'Classic Lorem Ipsum text',
    ],
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generator', 'dummy'],
    popular: true,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512) from any text.',
    category: 'security',
    icon: '#️⃣',
    features: [
      'MD5 hash generation',
      'SHA-1 hash generation',
      'SHA-256 hash generation',
      'SHA-512 hash generation',
      'All hashes generated simultaneously',
      'Copy individual or all hashes',
    ],
    keywords: ['hash', 'md5', 'sha', 'sha1', 'sha256', 'sha512', 'checksum', 'crypto'],
    popular: false,
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text between different cases: uppercase, lowercase, camelCase, snake_case, and more.',
    category: 'text-transformers',
    icon: '🔤',
    features: [
      'UPPERCASE conversion',
      'lowercase conversion',
      'Title Case conversion',
      'camelCase conversion',
      'PascalCase conversion',
      'snake_case conversion',
      'kebab-case conversion',
      'CONSTANT_CASE conversion',
      'Sentence case conversion',
    ],
    keywords: ['case', 'convert', 'uppercase', 'lowercase', 'camel', 'snake', 'kebab', 'pascal'],
    popular: false,
  },
  {
    id: 'text-diff-checker',
    name: 'Text Diff Checker',
    description: 'Compare two texts side-by-side. Find differences in lines, words, and characters.',
    category: 'text-transformers',
    icon: '📊',
    features: [
      'Side-by-side comparison',
      'Line difference count',
      'Word difference count',
      'Character difference count',
      'Detailed statistics',
      'Clear visualization',
    ],
    keywords: ['diff', 'compare', 'difference', 'text', 'compare', 'checker'],
    popular: false,
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter & Minifier',
    description: 'Format and beautify HTML code. Minify HTML to reduce file size.',
    category: 'formatters',
    icon: '</>',
    features: [
      'Format HTML with proper indentation',
      'Minify HTML (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Syntax preservation',
      'Fast processing',
    ],
    keywords: ['html', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: false,
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter & Minifier',
    description: 'Format and beautify CSS code. Minify CSS to reduce file size.',
    category: 'formatters',
    icon: '🎨',
    features: [
      'Format CSS with proper indentation',
      'Minify CSS (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Preserve CSS rules',
      'Fast processing',
    ],
    keywords: ['css', 'format', 'minify', 'beautify', 'formatter', 'compress', 'stylesheet'],
    popular: false,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor & Previewer',
    description: 'Write and preview Markdown in real-time. See your formatted content as you type.',
    category: 'text-transformers',
    icon: '📝',
    features: [
      'Live HTML preview',
      'Support for headers, bold, italic',
      'Code blocks and inline code',
      'Links and lists',
      'Split-panel view',
      'Instant rendering',
    ],
    keywords: ['markdown', 'md', 'editor', 'preview', 'html', 'formatting'],
    popular: true,
  },
  {
    id: 'color-picker',
    name: 'Color Picker & Converter',
    description: 'Pick colors and convert between HEX, RGB, and HSL formats instantly.',
    category: 'conversion',
    icon: '🎨',
    features: [
      'Visual color picker',
      'HEX color codes',
      'RGB color values',
      'HSL color values',
      'Copy any format',
      'Live color preview',
    ],
    keywords: ['color', 'picker', 'hex', 'rgb', 'hsl', 'converter', 'palette'],
    popular: true,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates. Supports ISO 8601 format.',
    category: 'conversion',
    icon: '🕐',
    features: [
      'Unix to Date conversion',
      'Date to Unix conversion',
      'ISO 8601 format support',
      'Current timestamp display',
      'Formatted date output',
      'Use current time button',
    ],
    keywords: ['timestamp', 'unix', 'date', 'time', 'convert', 'epoch', 'iso'],
    popular: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester & Validator',
    description: 'Test regular expressions with live matching. Supports flags and pattern validation.',
    category: 'text-transformers',
    icon: '🔍',
    features: [
      'Live regex testing',
      'Pattern validation',
      'Global, ignore case, multiline flags',
      'Match highlighting',
      'Match count and results',
      'Common flag presets',
    ],
    keywords: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test', 'validate'],
    popular: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder & Inspector',
    description: 'Decode and inspect JSON Web Tokens (JWT). View header, payload, and signature.',
    category: 'security',
    icon: '🔓',
    features: [
      'Decode JWT tokens',
      'Display header and payload',
      'Show signature',
      'Parse standard claims (iat, exp, nbf)',
      'Expiration checking',
      'Copy decoded parts',
    ],
    keywords: ['jwt', 'json web token', 'decode', 'inspect', 'token', 'auth', 'security'],
    popular: true,
  },
  {
    id: 'javascript-formatter',
    name: 'JavaScript Formatter & Minifier',
    description: 'Format and beautify JavaScript code. Minify JS to reduce file size.',
    category: 'formatters',
    icon: '⚡',
    features: [
      'Format JavaScript with proper indentation',
      'Minify JavaScript (remove whitespace & comments)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Syntax preservation',
      'Fast processing',
    ],
    keywords: ['javascript', 'js', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: true,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries. Proper indentation and keyword capitalization.',
    category: 'formatters',
    icon: '💾',
    features: [
      'Format SQL with proper indentation',
      'Keyword capitalization',
      'Support for common SQL operations',
      'JOIN formatting',
      'Nested query indentation',
      'Copy formatted SQL',
    ],
    keywords: ['sql', 'format', 'beautify', 'query', 'database', 'formatter'],
    popular: true,
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs. Download as PNG image.',
    category: 'generators',
    icon: '📱',
    features: [
      'Generate QR codes from any text',
      'URL encoding support',
      'Configurable size (128px, 256px, 512px)',
      'Download as PNG',
      'Instant generation',
      'Visual preview',
    ],
    keywords: ['qr', 'qr code', 'barcode', 'generate', 'url', 'mobile'],
    popular: true,
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64 Converter',
    description: 'Convert images to Base64 strings. Perfect for embedding in HTML, CSS, or JSON.',
    category: 'conversion',
    icon: '🖼️',
    features: [
      'Upload any image format',
      'Convert to Base64 string',
      'Image preview',
      'File size information',
      'Copy Base64 string',
      'Support for all image types',
    ],
    keywords: ['image', 'base64', 'convert', 'encode', 'embed', 'data uri'],
    popular: true,
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions. See human-readable schedules.',
    category: 'text-transformers',
    icon: '⏰',
    features: [
      'Parse cron expressions',
      'Human-readable descriptions',
      'Expression validation',
      'Common presets',
      'Part-by-part breakdown',
      'Schedule explanation',
    ],
    keywords: ['cron', 'schedule', 'parser', 'expression', 'time', 'job', 'task'],
    popular: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter & Minifier',
    description: 'Format and beautify XML. Minify XML to reduce file size.',
    category: 'formatters',
    icon: '📋',
    features: [
      'Format XML with proper indentation',
      'Minify XML (remove whitespace)',
      'Configurable indentation (2/4 spaces)',
      'Copy and download formatted code',
      'Preserve XML structure',
      'Fast processing',
    ],
    keywords: ['xml', 'format', 'minify', 'beautify', 'formatter', 'compress'],
    popular: true,
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate JSON Web Tokens with custom payload and expiration.',
    category: 'security',
    icon: '🔑',
    features: [
      'Generate JWT tokens',
      'Custom payload (JSON)',
      'Configurable secret key',
      'Expiration time presets',
      'View token parts (header, payload, signature)',
      'Copy generated token',
    ],
    keywords: ['jwt', 'json web token', 'generate', 'token', 'auth', 'security'],
    popular: true,
  },
  {
    id: 'csv-json-converter',
    name: 'CSV to JSON Converter',
    description: 'Convert between CSV and JSON formats. Bi-directional conversion.',
    category: 'conversion',
    icon: '🔄',
    features: [
      'CSV to JSON conversion',
      'JSON to CSV conversion',
      'Bi-directional with swap',
      'Auto-detect headers',
      'Number type parsing',
      'Quote handling for commas',
    ],
    keywords: ['csv', 'json', 'convert', 'converter', 'data', 'table', 'spreadsheet'],
    popular: true,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords with customizable options.',
    category: 'generators',
    icon: '🔐',
    features: [
      'Cryptographically secure generation',
      'Adjustable length (4-64 characters)',
      'Uppercase/lowercase options',
      'Numbers and symbols',
      'Password strength indicator',
      'One-click copy',
    ],
    keywords: ['password', 'generate', 'generator', 'secure', 'random', 'strong'],
    popular: true,
  },
  {
    id: 'json-yaml-converter',
    name: 'JSON to YAML Converter',
    description: 'Convert between JSON and YAML formats. Bi-directional conversion.',
    category: 'conversion',
    icon: '↔️',
    features: [
      'JSON to YAML conversion',
      'YAML to JSON conversion',
      'Bi-directional with swap',
      'Configurable YAML indentation',
      'Syntax examples included',
      'Comment preservation (YAML)',
    ],
    keywords: ['json', 'yaml', 'yml', 'convert', 'converter', 'config', 'configuration'],
    popular: true,
  },
  {
    id: 'html-entity-converter',
    name: 'HTML Entity Encoder & Decoder',
    description: 'Encode and decode HTML entities. Convert special characters to/from HTML entities.',
    category: 'conversion',
    icon: '&lt;&gt;',
    features: [
      'Encode HTML entities',
      'Decode HTML entities',
      'Common entities reference',
      'Bi-directional conversion',
      'Handles <, >, &, ", \'',
      'Copy and download results',
    ],
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'unescape', 'special characters'],
    popular: true,
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal bases.',
    category: 'conversion',
    icon: '🔢',
    features: [
      'Binary (Base 2) conversion',
      'Octal (Base 8) conversion',
      'Decimal (Base 10) conversion',
      'Hexadecimal (Base 16) conversion',
      'Quick reference guide',
      'Instant multi-base output',
    ],
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hexadecimal', 'hex', 'converter'],
    popular: true,
  },
  {
    id: 'text-escaper',
    name: 'Text Escape & Unescape',
    description: 'Escape and unescape text for JavaScript, JSON, XML, and URL contexts.',
    category: 'text-transformers',
    icon: '\\n',
    features: [
      'JavaScript string escaping',
      'JSON string escaping',
      'XML/HTML entity escaping',
      'URL encoding/decoding',
      'Bi-directional conversion',
      'Common sequences reference',
    ],
    keywords: ['escape', 'unescape', 'javascript', 'json', 'xml', 'url', 'string', 'encode'],
    popular: true,
  },
  {
    id: 'jsonpath-tester',
    name: 'JSONPath Tester',
    description: 'Test JSONPath expressions and query JSON data. Extract values from JSON.',
    category: 'text-transformers',
    icon: '🔍',
    features: [
      'Evaluate JSONPath queries',
      'Support for basic paths',
      'Array indexing',
      'Object property access',
      'Example paths included',
      'Syntax guide',
    ],
    keywords: ['json', 'jsonpath', 'path', 'query', 'extract', 'tester', 'evaluate'],
    popular: true,
  },
  {
    id: 'string-counter',
    name: 'String Counter',
    description: 'Count characters, words, lines, sentences, and more. Detailed text statistics.',
    category: 'text-transformers',
    icon: '🔢',
    features: [
      'Character count (with/without spaces)',
      'Word count',
      'Line and paragraph count',
      'Sentence count',
      'Byte count',
      'Reading & speaking time estimates',
    ],
    keywords: ['counter', 'count', 'character', 'word', 'line', 'statistics', 'text', 'length'],
    popular: true,
  },
  {
    id: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines of text alphabetically, numerically, or by length. Ascending or descending.',
    category: 'text-transformers',
    icon: '🔤',
    features: [
      'Alphabetical sorting',
      'Numerical sorting',
      'Sort by line length',
      'Ascending/descending order',
      'Case-sensitive option',
      'Line-by-line processing',
    ],
    keywords: ['sort', 'order', 'alphabetical', 'numerical', 'length', 'ascending', 'descending', 'text'],
    popular: true,
  },
  {
    id: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove duplicate lines from text. Keep only unique lines with statistics.',
    category: 'text-transformers',
    icon: '🗑️',
    features: [
      'Remove duplicate lines',
      'Case-sensitive option',
      'Preserve line order',
      'Show statistics',
      'Count duplicates removed',
      'Fast processing',
    ],
    keywords: ['duplicate', 'unique', 'remove', 'filter', 'dedupe', 'lines', 'text'],
    popular: true,
  },
  {
    id: 'random-string-generator',
    name: 'Random String Generator',
    description: 'Generate cryptographically secure random strings. Multiple character types supported.',
    category: 'generators',
    icon: '🎲',
    features: [
      'Alphanumeric strings',
      'Alphabetic only',
      'Numeric only',
      'Hexadecimal',
      'Custom character sets',
      'Cryptographically secure (Web Crypto API)',
    ],
    keywords: ['random', 'generator', 'string', 'password', 'token', 'api key', 'crypto', 'secure'],
    popular: true,
  },
  {
    id: 'unicode-character-finder',
    name: 'Unicode Character Finder',
    description: 'Browse and search Unicode characters. Copy symbols, arrows, math symbols, and more.',
    category: 'text-transformers',
    icon: '🔍',
    features: [
      'Browse by category',
      'Search by name or code',
      'Copy to clipboard',
      'Common symbols included',
      'Unicode code points',
      'Arrows, math, shapes, punctuation',
    ],
    keywords: ['unicode', 'character', 'symbol', 'emoji', 'special', 'arrow', 'math', 'copy'],
    popular: true,
  },
  {
    id: 'backslash-escaper',
    name: 'Backslash Escape & Unescape',
    description: 'Add or remove backslash escapes from text. Escape quotes, newlines, tabs, and more.',
    category: 'text-transformers',
    icon: '\\',
    features: [
      'Add backslash escapes',
      'Remove backslash escapes',
      'Escape quotes',
      'Escape newlines and tabs',
      'Bi-directional conversion',
      'Common escapes reference',
    ],
    keywords: ['backslash', 'escape', 'unescape', 'quotes', 'newline', 'tab', 'string', 'literal'],
    popular: true,
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate URL-friendly slugs from text. Perfect for blog posts, articles, and SEO.',
    category: 'text-transformers',
    icon: '🔗',
    features: [
      'URL-friendly formatting',
      'Remove special characters',
      'Custom separator (hyphen, underscore, dot)',
      'Lowercase option',
      'Remove accents and diacritics',
      'Preview URL',
    ],
    keywords: ['slug', 'url', 'seo', 'permalink', 'friendly', 'sanitize', 'blog', 'article'],
    popular: true,
  },
  {
    id: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse text by characters, words, or lines. Multiple reversal modes.',
    category: 'text-transformers',
    icon: '🔄',
    features: [
      'Reverse by characters',
      'Reverse by words',
      'Reverse by lines',
      'Visual mode examples',
      'Instant processing',
      'Preserve formatting options',
    ],
    keywords: ['reverse', 'flip', 'backwards', 'mirror', 'text', 'string', 'words', 'lines'],
    popular: true,
  },
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'Remove extra whitespace from text. Clean leading, trailing, and multiple spaces.',
    category: 'text-transformers',
    icon: '🧹',
    features: [
      'Remove leading spaces',
      'Remove trailing spaces',
      'Remove multiple consecutive spaces',
      'Remove all spaces',
      'Remove line breaks',
      'Flexible options',
    ],
    keywords: ['whitespace', 'trim', 'clean', 'spaces', 'remove', 'normalize', 'format'],
    popular: true,
  },
  {
    id: 'binary-text-converter',
    name: 'Binary Text Converter',
    description: 'Convert text to binary and vice versa. 8-bit ASCII binary encoding.',
    category: 'conversion',
    icon: '💾',
    features: [
      'Text to binary conversion',
      'Binary to text conversion',
      '8-bit ASCII encoding',
      'Bi-directional conversion',
      'Binary reference guide',
      'Educational examples',
    ],
    keywords: ['binary', 'text', 'convert', 'encode', 'decode', 'ascii', '8-bit', 'bits'],
    popular: true,
  },
  {
    id: 'morse-code-converter',
    name: 'Morse Code Converter',
    description: 'Convert text to Morse code and vice versa. International Morse Code standard.',
    category: 'conversion',
    icon: '📡',
    features: [
      'Text to Morse conversion',
      'Morse to text conversion',
      'International standard',
      'Complete Morse reference',
      'A-Z, 0-9, punctuation',
      'SOS and emergency signals',
    ],
    keywords: ['morse', 'code', 'convert', 'telegraph', 'radio', 'ham', 'sos', 'signal'],
    popular: true,
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    description: 'Convert Markdown to HTML with preview. Supports headers, bold, italic, links, and more.',
    category: 'conversion',
    icon: '📄',
    features: [
      'Markdown to HTML conversion',
      'Live preview mode',
      'Headers, bold, italic',
      'Links and images',
      'Lists and code blocks',
      'Syntax reference guide',
    ],
    keywords: ['markdown', 'html', 'convert', 'md', 'preview', 'render', 'format'],
    popular: true,
  },
  {
    id: 'json-xml-converter',
    name: 'JSON to XML Converter',
    description: 'Convert between JSON and XML formats. Bi-directional conversion.',
    category: 'conversion',
    icon: '🔄',
    features: [
      'JSON to XML conversion',
      'XML to JSON conversion',
      'Bi-directional conversion',
      'Preserves data structure',
      'Handles nested objects',
      'Arrays and attributes support',
    ],
    keywords: ['json', 'xml', 'convert', 'transform', 'parse', 'serialize'],
    popular: true,
  },
  {
    id: 'url-parser',
    name: 'URL Parser & Analyzer',
    description: 'Parse URLs into components. Extract protocol, hostname, path, query parameters, and hash.',
    category: 'text-transformers',
    icon: '🔗',
    features: [
      'Parse URL components',
      'Extract query parameters',
      'Decode URL encoding',
      'Protocol and hostname',
      'Pathname and hash',
      'Visual component breakdown',
    ],
    keywords: ['url', 'parse', 'query', 'parameters', 'decode', 'analyze', 'uri'],
    popular: true,
  },
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and validate YAML syntax. Clean up indentation and structure.',
    category: 'formatters',
    icon: '📋',
    features: [
      'Format YAML syntax',
      'Consistent indentation',
      'Syntax validation',
      'Configuration file support',
      'Docker, Kubernetes, CI/CD',
      'YAML syntax guide',
    ],
    keywords: ['yaml', 'format', 'validate', 'indent', 'config', 'configuration', 'yml'],
    popular: true,
  },
  {
    id: 'hex-color-converter',
    name: 'Hex Color Converter',
    description: 'Convert between HEX, RGB, and HSL color formats. Live color preview.',
    category: 'conversion',
    icon: '🎨',
    features: [
      'HEX to RGB conversion',
      'RGB to HEX conversion',
      'HSL color support',
      'Live color preview',
      'Interactive inputs',
      'All formats displayed',
    ],
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker', 'format', 'css'],
    popular: true,
  },
  {
    id: 'json-diff-viewer',
    name: 'JSON Diff Viewer',
    description: 'Compare two JSON objects and visualize differences. Side-by-side comparison.',
    category: 'text-transformers',
    icon: '🔍',
    features: [
      'Compare two JSON objects',
      'Visual difference highlighting',
      'Added/Removed/Changed detection',
      'Path-based comparison',
      'Detailed change report',
      'Color-coded results',
    ],
    keywords: ['json', 'diff', 'compare', 'difference', 'merge', 'viewer', 'changes'],
    popular: true,
  },
  {
    id: 'template-formatter',
    name: 'Template String Formatter',
    description: 'Format template strings with variable substitution. Supports multiple syntaxes.',
    category: 'text-transformers',
    icon: '📝',
    features: [
      'Variable substitution',
      '{{variable}} syntax support',
      '${variable} syntax support',
      'key=value variable input',
      'Email template formatting',
      'Document generation',
    ],
    keywords: ['template', 'format', 'variable', 'substitute', 'placeholder', 'string', 'handlebars'],
    popular: true,
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    description: 'Convert between bytes, KB, MB, GB, TB, and PB. Binary (1024-based) conversion.',
    category: 'conversion',
    icon: '💾',
    features: [
      'Convert file sizes',
      'B, KB, MB, GB, TB, PB support',
      'Binary (1024) calculation',
      'Precise decimal results',
      'All units displayed',
      'Common size reference',
    ],
    keywords: ['file', 'size', 'convert', 'bytes', 'kb', 'mb', 'gb', 'tb', 'storage'],
    popular: true,
  },
  {
    id: 'unix-permissions',
    name: 'Unix Permissions Calculator',
    description: 'Convert between chmod numbers and rwx notation. Permission builder included.',
    category: 'generators',
    icon: '🔐',
    features: [
      'Chmod to rwx conversion',
      'rwx to chmod conversion',
      'Interactive permission builder',
      'Common patterns reference',
      'User/Group/Other breakdown',
      'Permission explanations',
    ],
    keywords: ['unix', 'chmod', 'permissions', 'rwx', 'linux', 'file', 'access', '755'],
    popular: true,
  },
  {
    id: 'email-url-validator',
    name: 'Email & URL Validator',
    description: 'Validate email addresses and URLs. Comprehensive format checking with error messages.',
    category: 'text-transformers',
    icon: '✅',
    features: [
      'Email validation',
      'URL validation',
      'Format checking',
      'Detailed error messages',
      'Length validation',
      'Protocol checking',
    ],
    keywords: ['email', 'url', 'validate', 'check', 'verify', 'format', 'regex', 'validation'],
    popular: true,
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Parse user agent strings to extract browser, OS, and device information.',
    category: 'text-transformers',
    icon: '🌐',
    features: [
      'Parse user agent strings',
      'Detect browser and version',
      'Identify operating system',
      'Device type detection',
      'Auto-detect current browser',
      'Example user agents included',
    ],
    keywords: ['user agent', 'ua', 'browser', 'detection', 'parser', 'device', 'os', 'mobile'],
    popular: true,
  },
  {
    id: 'gitignore-generator',
    name: 'Gitignore Generator',
    description: 'Generate .gitignore files for different languages and frameworks.',
    category: 'generators',
    icon: '📋',
    features: [
      'Multiple language templates',
      'Node.js, Python, Java, React',
      'OS-specific ignores (macOS, Windows)',
      'Editor configs (VS Code)',
      'Combine multiple templates',
      'Ready to use patterns',
    ],
    keywords: ['gitignore', 'git', 'ignore', 'template', 'generator', 'node', 'python', 'java'],
    popular: true,
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code by removing comments, whitespace, and unnecessary characters.',
    category: 'formatters',
    icon: '🎨',
    features: [
      'Remove comments',
      'Strip whitespace',
      'Optimize semicolons',
      'Compression statistics',
      'Byte savings calculation',
      'Percentage reduction display',
    ],
    keywords: ['css', 'minify', 'compress', 'optimize', 'reduce', 'size', 'minifier'],
    popular: true,
  },
  {
    id: 'javascript-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code by removing comments and whitespace. Basic minification.',
    category: 'formatters',
    icon: '⚡',
    features: [
      'Remove comments',
      'Strip whitespace',
      'Basic compression',
      'Compression statistics',
      'Byte savings calculation',
      'Note: For production, use Terser/UglifyJS',
    ],
    keywords: ['javascript', 'js', 'minify', 'compress', 'optimize', 'reduce', 'minifier'],
    popular: true,
  },
  {
    id: 'text-statistics',
    name: 'Text Statistics Calculator',
    description: 'Analyze text for word count, reading time, and detailed statistics.',
    category: 'text-transformers',
    icon: '📊',
    features: [
      'Character count (with/without spaces)',
      'Word, sentence, paragraph count',
      'Reading time estimate',
      'Speaking time estimate',
      'Average word length',
      'Longest word detection',
    ],
    keywords: ['text', 'statistics', 'word count', 'reading time', 'analysis', 'counter', 'words'],
    popular: true,
  },
  {
    id: 'rot13-cipher',
    name: 'ROT13 Cipher',
    description: 'Encode and decode text using ROT13 or custom Caesar cipher shifts.',
    category: 'text-transformers',
    icon: '🔐',
    features: [
      'ROT13 encoding/decoding',
      'Custom Caesar cipher shifts (1-25)',
      'Bi-directional conversion',
      'Preserve non-alphabetic characters',
      'Educational cipher reference',
      'Classic cryptography demo',
    ],
    keywords: ['rot13', 'caesar', 'cipher', 'encode', 'decode', 'encryption', 'cryptography', 'shift'],
    popular: true,
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between decimal numbers and Roman numerals (1-3999).',
    category: 'conversion',
    icon: '🏛️',
    features: [
      'Decimal to Roman conversion',
      'Roman to decimal conversion',
      'Range: 1-3999',
      'Subtraction notation support',
      'Complete numeral reference',
      'Historical examples included',
    ],
    keywords: ['roman', 'numeral', 'convert', 'decimal', 'number', 'ancient', 'latin'],
    popular: true,
  },
  {
    id: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert between CSS units: px, rem, em, pt, cm, mm, and inches.',
    category: 'conversion',
    icon: '📐',
    features: [
      'Convert px, rem, em, pt, cm, mm, in',
      'Adjustable base font size',
      'Real-time conversion',
      'All unit results displayed',
      'CSS unit reference guide',
      'Responsive design helper',
    ],
    keywords: ['css', 'unit', 'convert', 'px', 'rem', 'em', 'responsive', 'font', 'size'],
    popular: true,
  },
  {
    id: 'ip-address-tools',
    name: 'IP Address Tools',
    description: 'Convert IPv4 addresses to decimal, binary, and hexadecimal formats.',
    category: 'conversion',
    icon: '🌐',
    features: [
      'IPv4 to decimal conversion',
      'Binary representation',
      'Hexadecimal format',
      'Octet breakdown',
      'Reverse conversion (decimal to IP)',
      'Common IP examples',
    ],
    keywords: ['ip', 'ipv4', 'address', 'convert', 'decimal', 'binary', 'hex', 'network'],
    popular: true,
  },
  {
    id: 'color-name-lookup',
    name: 'Color Name Lookup',
    description: 'Search and convert CSS color names to HEX and RGB values.',
    category: 'conversion',
    icon: '🎨',
    features: [
      'Search 140+ CSS color names',
      'Name to HEX conversion',
      'RGB values display',
      'Live color preview',
      'Color swatch grid',
      'Copy HEX to clipboard',
    ],
    keywords: ['color', 'name', 'css', 'hex', 'rgb', 'search', 'lookup', 'palette'],
    popular: true,
  },
]

// Helper function to get tool by ID
export function getToolById(id: string): ToolConfig | undefined {
  return toolRegistry.find((tool) => tool.id === id)
}

// Helper function to get tools by category
export function getToolsByCategory(category: string): ToolConfig[] {
  return toolRegistry.filter((tool) => tool.category === category)
}

// Helper function to get popular tools
export function getPopularTools(): ToolConfig[] {
  return toolRegistry.filter((tool) => tool.popular)
}
